### ISSUE TITLE
Support Vertex Color OBJ Format

### ISSUE THREAD

**Issue by arpu** [thisistherk/fast_obj#28]
Hey,
would it be possible to add support for 
#obj file generated by SculptrVR
#Vertex format:  v   x  y  z  r  g  b#Vertex colors are not supported by all programs.

sample is 
https://www.shapeways.com/forum/t/vertex-color-obj-format.42061/

**Comment by thisistherk** [comment]
Yep, sounds useful.  Probably be a while before I'll get around to it though.  Happy to take contributions in the meantime :)

**Comment by arpu** [comment]
this would be greate!   @zeux  could add this to meshoptimzer using fast_obj  

( i have to less knowledge for a PR :/ )

**Comment by maxrigout** [comment]
@arpu I've created a PR for this issue, feel free to check it out and let me know if you find any issues :)
