### ISSUE TITLE
We ported FastObj to Unity

### ISSUE THREAD

**Issue by Strepto** [thisistherk/fast_obj#34]
Just writing here that we used fast_obj in an Unity 3D package for faster Obj loading in Unity in the project I'm working in. If anyone is interested in that you can find it here: https://github.com/equinor/FastObjUnity

It should™ work at runtime in Unity, and is quite fast and nice for most common ".obj" files if you want to quickly preview or use them in a Unity context.

Thanks for a great, fast tool 👍

**Comment by Strepto** [comment]
Closing this issue, as its not really a problem. Just thought it might be nice to know about :)

**Comment by thisistherk** [comment]
Awesome - glad you've found it useful :)
