### ISSUE TITLE
Confused about OpenGL usage

### ISSUE THREAD

**Issue by somerandompiggo** [thisistherk/fast_obj#44]
I'm testing the library with a cube OBJ exported from Blender. It seems to load fine, but loading it into a VBO and EBO using this code doesn't work properly:

```
glGenVertexArrays(1, &mesh->VAO);
glBindVertexArray(mesh->VAO);

glGenBuffers(1, &mesh->VBO);
glBindBuffer(GL_ARRAY_BUFFER, mesh->VBO);
glBufferData(GL_ARRAY_BUFFER, objmesh->position_count * sizeof(float) * 3, objmesh->positions, GL_STATIC_DRAW);

glGenBuffers(1, &mesh->EBO);
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mesh->EBO);
glBufferData(GL_ELEMENT_ARRAY_BUFFER, objmesh->index_count * sizeof(unsigned int), objmesh->indices, GL_STATIC_DRAW);
```

When drawing with GL_TRIANGLES, nothing is displayed but if I use GL_LINES they go out from the origin to the 8 vertices of the cube. I think it's an issue with the indices, but I've been trying for days and I can't seem to figure out why

![image](https://github.com/thisistherk/fast_obj/assets/45299425/0f44e148-d965-4d79-a58a-50c62392ebd3)
(view from inside renderdoc)

Thanks!

cube.obj:
```
# Blender 4.0.1
# www.blender.org
o Cube
v 1.000000 1.000000 -1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 1.000000
s 0
f 5 3 1
f 3 8 4
f 7 6 8
f 2 8 6
f 1 4 2
f 5 2 6
f 5 7 3
f 3 7 8
f 7 5 6
f 2 4 8
f 1 3 4
f 5 1 2
```

**Comment by thisistherk** [comment]
Not really sure, but you might get something like that if you passed `GL_UNSIGNED_SHORT` to `glDrawElements` rather than `GL_UNSIGNED_INT`.  `fastObjMesh::positions[0]` is a vertex at (0, 0, 0) - all valid indices are 1 based so it's never actually referenced, but if you got the size wrong to the `glDrawElements` call GL would see lots of 0 indices and might give you something like you describe.  Hopefully give you something to look for anyway...

**Comment by somerandompiggo** [comment]
Had another crack at it, no luck so far. Here is a more complete snippet, I hope it helps since my last one was really minimal

Initialization:
```c
fastObjMesh* objmesh = fast_obj_read(path);
if (objmesh == NULL) {
    printf("Error loading OBJ file with path: %s\n", path);
    return;
}

mesh->count = objmesh->index_count;

glGenVertexArrays(1, &mesh->VAO);
glBindVertexArray(mesh->VAO);

glGenBuffers(1, &mesh->VBO);
glBindBuffer(GL_ARRAY_BUFFER, mesh->VBO);
glBufferData(GL_ARRAY_BUFFER, objmesh->position_count * sizeof(float) * 3, objmesh->positions, GL_STATIC_DRAW);

glGenBuffers(1, &mesh->EBO);
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mesh->EBO);
glBufferData(GL_ELEMENT_ARRAY_BUFFER, objmesh->index_count * sizeof(unsigned int), objmesh->indices, GL_STATIC_DRAW);

glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
glEnableVertexAttribArray(0);
```

Draw loop:
```c
glBindVertexArray(mesh->VAO);
glDrawElements(GL_TRIANGLES, mesh->count, GL_UNSIGNED_INT, 0);
```

**Comment by somerandompiggo** [comment]
Sorry, wrote my own loader to test. Exact same result, not an issue with the library. Will edit this comment when I find a fix

**Comment by yegorxyz** [comment]
For anyone who is still looking for a solution to this problem:

The external data structure to which I was passing the vertices indexed from 0, but the fastObj data indexes from 1.
This is why you get strange geometry pointing towards (0.0, 0.0, 0.0).

I simply subtracted 1 from each fastObj index in a for loop before passing it to the external data and was able to solve the issue.
