### ISSUE TITLE
Feature request: new release

### ISSUE THREAD

**Issue by FedericoCeratto** [thisistherk/fast_obj#47]
Hello and thank you for developing fast_obj.
There has been many improvements since the last release and the library is used in Organic Maps among other projects.  Could you consider doing a release shortly (or a RC) please?

Thanks!

**Comment by zeux** [comment]
Yeah this would be nice; [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf) is currently using mostly-latest master instead of a numbered release as the changes since 1.2 are important/valuable.

**Comment by thisistherk** [comment]
Sorry folks, life getting in the way :)  I'll try and get to it some time in the next week or two (along with merging in that pending MR).

**Comment by thisistherk** [comment]
Done now.  Thanks for prodding me - hopefully I haven't messed it up!
