### ISSUE TITLE
Would it make sense to unify materials/vertices/indices arrays?

### ISSUE THREAD

**Issue by zeux** [thisistherk/fast_obj#5]
I'm interested in making a PR that moves fastObjGroup::materials, fastObjGroup::vertices and fastObjGroup::indices to fastObjMesh (probably calling them face_materials, face_vertices and face_indices), and changing fastObjGroup to something along the lines of:

```
typedef struct
{
    /* Group name */
    char*                       name;

    /* Number of faces */
    unsigned int                face_count;

    /* Offset of face data in fastObjMesh::face_* arrays */
    size_t                           face_offset;

} fastObjGroup;
```

Would that make sense / is that PR likely to be merged? The reason I'd like to make this change is that it makes parsing .obj easier for clients that don't care about the group data - since group data is completely extraneous and doesn't always provide meaningful splitting (material definition is per-face, not per-group), it seems like in most cases you'd want to ignore it.

I'm looking at replacing a custom .obj file parser (because the world doesn't need another .obj loader :P) with this one in several places where group data is inessential and this is the last small usability barrier left.

**Comment by thisistherk** [comment]
Yeah, makes sense to me.  Don't really remember, but suspect I just roughly copied what tinyobjloader did without giving it too much (or any!) real thought.   But sounds like that'd give you the best of both worlds - treat it as a single mesh if you want, but the group data is still there if you need it...

**Comment by zeux** [comment]
Looks like tinyobjloader-c actually has the same structure I was thinking of :) https://github.com/syoyo/tinyobjloader-c/blob/master/tinyobj_loader_c.h#L55-L59

The C++ version has a structure similar to the current one, with indices split per shape.
